In [2]:
import pandas as pd

In [8]:
# Concatenation

df1 = pd.DataFrame({
    "id" : [1, 2, 3],
    "name" : ["Adam", "Eve", "Bob"]
})

df2 = pd.DataFrame({
    "id" : [4, 5, 6],
    "name" : ["Charlie", "Faster", "Gilian"]
})

pd.concat([df1, df2]) # row
pd.concat([df1, df2], ignore_index=True) # row

pd.concat([df1, df2], axis = 1) # col

   id  name  id     name
0   1  Adam   4  Charlie
1   2   Eve   5   Faster
2   3   Bob   6   Gilian

In [4]:
df1

   id  name
0   1  Adam
1   2   Eve
2   3   Bob

In [5]:
df2

   id     name
0   4  Charlie
1   5   Faster
2   6   Gilian